// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: ledger.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "ledger";

export interface SubmitTransactionRequest {
  from: string;
  to: string;
  /** u128 as string */
  amount: string;
  asset: string;
  memo?:
    | string
    | undefined;
  /** crypto signature for authentication */
  signature: string;
}

export interface SubmitTransactionResponse {
  success: boolean;
  txHash: string;
  errorMessage: string;
}

export interface GetBalanceRequest {
  address: string;
  asset: string;
}

export interface GetBalanceResponse {
  /** u128 as string */
  balance: string;
  asset: string;
}

export interface GetStatementRequest {
  address: string;
  limit: string;
}

export interface TransactionRecord {
  txHash: string;
  from: string;
  to: string;
  amount: string;
  asset: string;
  timestamp: string;
  memo: string;
}

export interface GetStatementResponse {
  transactions: TransactionRecord[];
}

function createBaseSubmitTransactionRequest(): SubmitTransactionRequest {
  return { from: "", to: "", amount: "", asset: "", memo: undefined, signature: "" };
}

export const SubmitTransactionRequest: MessageFns<SubmitTransactionRequest> = {
  encode(message: SubmitTransactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.to !== "") {
      writer.uint32(18).string(message.to);
    }
    if (message.amount !== "") {
      writer.uint32(26).string(message.amount);
    }
    if (message.asset !== "") {
      writer.uint32(34).string(message.asset);
    }
    if (message.memo !== undefined) {
      writer.uint32(42).string(message.memo);
    }
    if (message.signature !== "") {
      writer.uint32(50).string(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubmitTransactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitTransactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.asset = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitTransactionRequest {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      asset: isSet(object.asset) ? globalThis.String(object.asset) : "",
      memo: isSet(object.memo) ? globalThis.String(object.memo) : undefined,
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
    };
  },

  toJSON(message: SubmitTransactionRequest): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.asset !== "") {
      obj.asset = message.asset;
    }
    if (message.memo !== undefined) {
      obj.memo = message.memo;
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    return obj;
  },

  create(base?: DeepPartial<SubmitTransactionRequest>): SubmitTransactionRequest {
    return SubmitTransactionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SubmitTransactionRequest>): SubmitTransactionRequest {
    const message = createBaseSubmitTransactionRequest();
    message.from = object.from ?? "";
    message.to = object.to ?? "";
    message.amount = object.amount ?? "";
    message.asset = object.asset ?? "";
    message.memo = object.memo ?? undefined;
    message.signature = object.signature ?? "";
    return message;
  },
};

function createBaseSubmitTransactionResponse(): SubmitTransactionResponse {
  return { success: false, txHash: "", errorMessage: "" };
}

export const SubmitTransactionResponse: MessageFns<SubmitTransactionResponse> = {
  encode(message: SubmitTransactionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.txHash !== "") {
      writer.uint32(18).string(message.txHash);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubmitTransactionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitTransactionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.txHash = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitTransactionResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      txHash: isSet(object.txHash) ? globalThis.String(object.txHash) : "",
      errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "",
    };
  },

  toJSON(message: SubmitTransactionResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.txHash !== "") {
      obj.txHash = message.txHash;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create(base?: DeepPartial<SubmitTransactionResponse>): SubmitTransactionResponse {
    return SubmitTransactionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SubmitTransactionResponse>): SubmitTransactionResponse {
    const message = createBaseSubmitTransactionResponse();
    message.success = object.success ?? false;
    message.txHash = object.txHash ?? "";
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseGetBalanceRequest(): GetBalanceRequest {
  return { address: "", asset: "" };
}

export const GetBalanceRequest: MessageFns<GetBalanceRequest> = {
  encode(message: GetBalanceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.asset !== "") {
      writer.uint32(18).string(message.asset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBalanceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBalanceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.asset = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBalanceRequest {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      asset: isSet(object.asset) ? globalThis.String(object.asset) : "",
    };
  },

  toJSON(message: GetBalanceRequest): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.asset !== "") {
      obj.asset = message.asset;
    }
    return obj;
  },

  create(base?: DeepPartial<GetBalanceRequest>): GetBalanceRequest {
    return GetBalanceRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBalanceRequest>): GetBalanceRequest {
    const message = createBaseGetBalanceRequest();
    message.address = object.address ?? "";
    message.asset = object.asset ?? "";
    return message;
  },
};

function createBaseGetBalanceResponse(): GetBalanceResponse {
  return { balance: "", asset: "" };
}

export const GetBalanceResponse: MessageFns<GetBalanceResponse> = {
  encode(message: GetBalanceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.balance !== "") {
      writer.uint32(10).string(message.balance);
    }
    if (message.asset !== "") {
      writer.uint32(18).string(message.asset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBalanceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBalanceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.balance = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.asset = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBalanceResponse {
    return {
      balance: isSet(object.balance) ? globalThis.String(object.balance) : "",
      asset: isSet(object.asset) ? globalThis.String(object.asset) : "",
    };
  },

  toJSON(message: GetBalanceResponse): unknown {
    const obj: any = {};
    if (message.balance !== "") {
      obj.balance = message.balance;
    }
    if (message.asset !== "") {
      obj.asset = message.asset;
    }
    return obj;
  },

  create(base?: DeepPartial<GetBalanceResponse>): GetBalanceResponse {
    return GetBalanceResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBalanceResponse>): GetBalanceResponse {
    const message = createBaseGetBalanceResponse();
    message.balance = object.balance ?? "";
    message.asset = object.asset ?? "";
    return message;
  },
};

function createBaseGetStatementRequest(): GetStatementRequest {
  return { address: "", limit: "0" };
}

export const GetStatementRequest: MessageFns<GetStatementRequest> = {
  encode(message: GetStatementRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.limit !== "0") {
      writer.uint32(16).uint64(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatementRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatementRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStatementRequest {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      limit: isSet(object.limit) ? globalThis.String(object.limit) : "0",
    };
  },

  toJSON(message: GetStatementRequest): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.limit !== "0") {
      obj.limit = message.limit;
    }
    return obj;
  },

  create(base?: DeepPartial<GetStatementRequest>): GetStatementRequest {
    return GetStatementRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetStatementRequest>): GetStatementRequest {
    const message = createBaseGetStatementRequest();
    message.address = object.address ?? "";
    message.limit = object.limit ?? "0";
    return message;
  },
};

function createBaseTransactionRecord(): TransactionRecord {
  return { txHash: "", from: "", to: "", amount: "", asset: "", timestamp: "0", memo: "" };
}

export const TransactionRecord: MessageFns<TransactionRecord> = {
  encode(message: TransactionRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txHash !== "") {
      writer.uint32(10).string(message.txHash);
    }
    if (message.from !== "") {
      writer.uint32(18).string(message.from);
    }
    if (message.to !== "") {
      writer.uint32(26).string(message.to);
    }
    if (message.amount !== "") {
      writer.uint32(34).string(message.amount);
    }
    if (message.asset !== "") {
      writer.uint32(42).string(message.asset);
    }
    if (message.timestamp !== "0") {
      writer.uint32(48).uint64(message.timestamp);
    }
    if (message.memo !== "") {
      writer.uint32(58).string(message.memo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransactionRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.txHash = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.asset = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.timestamp = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionRecord {
    return {
      txHash: isSet(object.txHash) ? globalThis.String(object.txHash) : "",
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      asset: isSet(object.asset) ? globalThis.String(object.asset) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "0",
      memo: isSet(object.memo) ? globalThis.String(object.memo) : "",
    };
  },

  toJSON(message: TransactionRecord): unknown {
    const obj: any = {};
    if (message.txHash !== "") {
      obj.txHash = message.txHash;
    }
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.asset !== "") {
      obj.asset = message.asset;
    }
    if (message.timestamp !== "0") {
      obj.timestamp = message.timestamp;
    }
    if (message.memo !== "") {
      obj.memo = message.memo;
    }
    return obj;
  },

  create(base?: DeepPartial<TransactionRecord>): TransactionRecord {
    return TransactionRecord.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TransactionRecord>): TransactionRecord {
    const message = createBaseTransactionRecord();
    message.txHash = object.txHash ?? "";
    message.from = object.from ?? "";
    message.to = object.to ?? "";
    message.amount = object.amount ?? "";
    message.asset = object.asset ?? "";
    message.timestamp = object.timestamp ?? "0";
    message.memo = object.memo ?? "";
    return message;
  },
};

function createBaseGetStatementResponse(): GetStatementResponse {
  return { transactions: [] };
}

export const GetStatementResponse: MessageFns<GetStatementResponse> = {
  encode(message: GetStatementResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.transactions) {
      TransactionRecord.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatementResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatementResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transactions.push(TransactionRecord.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStatementResponse {
    return {
      transactions: globalThis.Array.isArray(object?.transactions)
        ? object.transactions.map((e: any) => TransactionRecord.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetStatementResponse): unknown {
    const obj: any = {};
    if (message.transactions?.length) {
      obj.transactions = message.transactions.map((e) => TransactionRecord.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GetStatementResponse>): GetStatementResponse {
    return GetStatementResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetStatementResponse>): GetStatementResponse {
    const message = createBaseGetStatementResponse();
    message.transactions = object.transactions?.map((e) => TransactionRecord.fromPartial(e)) || [];
    return message;
  },
};

export interface LedgerService {
  SubmitTransaction(request: SubmitTransactionRequest): Promise<SubmitTransactionResponse>;
  GetBalance(request: GetBalanceRequest): Promise<GetBalanceResponse>;
  GetStatement(request: GetStatementRequest): Promise<GetStatementResponse>;
}

export const LedgerServiceServiceName = "ledger.LedgerService";
export class LedgerServiceClientImpl implements LedgerService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || LedgerServiceServiceName;
    this.rpc = rpc;
    this.SubmitTransaction = this.SubmitTransaction.bind(this);
    this.GetBalance = this.GetBalance.bind(this);
    this.GetStatement = this.GetStatement.bind(this);
  }
  SubmitTransaction(request: SubmitTransactionRequest): Promise<SubmitTransactionResponse> {
    const data = SubmitTransactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SubmitTransaction", data);
    return promise.then((data) => SubmitTransactionResponse.decode(new BinaryReader(data)));
  }

  GetBalance(request: GetBalanceRequest): Promise<GetBalanceResponse> {
    const data = GetBalanceRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBalance", data);
    return promise.then((data) => GetBalanceResponse.decode(new BinaryReader(data)));
  }

  GetStatement(request: GetStatementRequest): Promise<GetStatementResponse> {
    const data = GetStatementRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetStatement", data);
    return promise.then((data) => GetStatementResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
